{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers ''Access-Control-Expose-Headers:
      Location'';'
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Location,pragma,X-Language
    nginx.ingress.kubernetes.io/cors-allow-methods: GET,PUT,POST,DELETE,HEAD,OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
  name: {{ .Release.Name }}
  namespace: {{.Release.Namespace}}
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      {{- range .Values.ingressRoutes }}
      {{- $service := .service }}
      {{- $port := .port }}
      {{- range .paths }}
      - backend:
          service:
            name: {{ $service }}
            port:
              number: {{ $port }}
        path: {{ . }}
        pathType: Prefix
      {{- end }}
      {{- end }}
{{- end }}
