{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{.Release.Namespace}}
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      {{- range .Values.ingressRoutes }}
      {{- $service := .service }}
      {{- $port := .port }}
      {{- range .paths }}
      - backend:
          service:
            name: {{ $service }}
            port:
              number: {{ $port }}
        path: {{ . }}
        pathType: Prefix
      {{- end }}
      {{- end }}
{{- end }}
