nameOverride: ""
fullnameOverride: ""

replicaCount: 1

namespace: anyshare

nodeSelector: {}

env:
  publicProtocol: https
  privateProtocol: http

image:
  registry: ""
  pullPolicy: IfNotPresent
  repository: "as/isfwebthrift"
  tag: 1.0.0

service:
  enableDualStack: false 
  type: ClusterIP
  port: 18802
  containerPort: 8002
  oauthOn: true
  oauthClientID: ""
  oauthClientSecret: ""
  SECRET_KEY: ""
  sleep:
    tokenRefresh: 10
  sslOn: false
  certFile:
  keyFile:
  logger: stdout
  language: zh_CN
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 3
  oauth2:
    hydraPublicProtocol: https


aclOAuth:

depServices:
  isfwebthrift:
    publicHost: isfwebthrift
    publicPort: 18802
  isfweb:
    publicHost: isfweb
    publicPort: 18801
  sharemgnt:
    host: sharemgnt
    port: 9600
  sharemgnt-single:
    host: sharemgnt-single
    port: 9600
  eacp:
    publicHttpHost: eacp-public
    publicHttpPort: 9998
    privateHttpHost: eacp-private
    privateHttpPort: 9998
    thriftHost: eacp-thrift
    thriftPort: 9992
  hydra:
    publicHost: hydra-public
    publicPort: 4444
    administrativeHost: hydra-admin
    administrativePort: 4445
  user-management:
    publicHost: user-management-public
    publicPort: 30980
    privateHost: user-management-private
    privatePort: 30980
  authentication:
    publicHost: authentication-public
    publicPort: 30110
    privateHost: authentication-private
    privatePort: 30110
  ossgatewaymanager:
    privateHost: ossgatewaymanager-private
    privatePort: 9002
  audit-log:
    privateHost: audit-log-private
    privatePort: 30569

resources:
  requests:
    cpu: 10m
    memory: 130Mi

uwsgi:
  workers: 10