{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: copy-cfl-config
          args:
            - |
              cp /sysvol/apphome/lib64/cfl.config /cfl-config/cfl.config
              chown 0:5000 /cfl-config/cfl.config
              chmod 660 /cfl-config/cfl.config
          command:
            - /bin/sh
            - -c
          image: {{ .Values.image.registry }}/{{ .Values.image.service.repository }}:{{ .Values.image.service.tag }}
          imagePullPolicy: {{ .Values.image.service.pullPolicy }}
          volumeMounts:
            - mountPath: /cfl-config
              name: cfl-config
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.service.repository }}:{{ .Values.image.service.tag }}
          imagePullPolicy: {{ .Values.image.service.pullPolicy }}
          env:
            {{- if .Values.service.logger}}
              - name: LOGOUT
                value: {{ .Values.service.logger | quote}}
            {{- end}}
            {{- if .Values.env.language}}
              - name: LANG
                value: {{ .Values.env.language | quote}}
              - name: LC_ALL
                value: {{ .Values.env.language | quote}}
            {{- end}}
            {{- if .Values.env.timezone}}
              - name: TZ
                value: {{ .Values.env.timezone | quote}}
            {{- end}}
              - name: EACP_ENV_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: DB_TYPE
                value:  {{ .Values.depServices.rds.type | quote }}
              - name:  DM_SVC_PATH
                value: /sysvol/conf/service_conf/
          ports:
            - name: eacppublic
              containerPort: {{ .Values.service.port }}
            - name: eacpprivate
              containerPort: {{add 1 .Values.service.port }}
            - name: eacpthrift
              containerPort: {{add 2 .Values.service.port }}
            - name: eacpbrpc1
              containerPort: {{add 3 .Values.service.port }}
            - name: eacpbrpc2
              containerPort: {{add 4 .Values.service.port }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  check_health() {
                    local port=$1
                    local status_code=$(curl -sf -w '%{http_code}' -o /dev/null http://localhost:$port/health/ready)
                    if [ "$status_code" -eq 200 ]; then
                      echo "Service on port $port is healthy"
                    else
                      echo "Service on port $port is unhealthy, status code: $status_code" >&2
                      exit 1
                    fi
                  }
                  check_health {{ .Values.service.port }}
                  check_health {{ add1 .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.service.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.service.readinessProbe.failureThreshold }}
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  check_health() {
                    local port=$1
                    local status_code=$(curl -sf -w '%{http_code}' -o /dev/null http://localhost:$port/health/alive)
                    if [ "$status_code" -eq 200 ]; then
                      echo "Service on port $port is healthy"
                    else
                      echo "Service on port $port is unhealthy, status code: $status_code" >&2
                      exit 1
                    fi
                  }
                  check_health {{ .Values.service.port }}
                  check_health {{ add1 .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.service.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.service.livenessProbe.failureThreshold }}
          # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
          # https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
          # 给负载均衡器和服务发现系统充分的“下线”时间。Pod 在即将被终止时，需要让其他服务
          # 发现机制（比如 Kubernetes Service）知道这个实例即将离线，以免继续将请求路由到它。
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /sysvol/conf/service_conf
            - name: {{ .Release.Name }}-secret
              mountPath: /sysvol/conf/secret_conf
            - name: wapi
              mountPath: /sysvol/.wapi
            - name: ipc
              mountPath: /var/ipc
            - name: tmp-volume
              mountPath: /tmp
            - name: brpc-volume
              mountPath: /sysvol/brpc/eacp
            - name: cfl-config
              mountPath: /sysvol/apphome/lib64/cfl.config
              subPath: cfl.config
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: {{ .Release.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-conf
            items:
            - key: language.conf
              path: language.conf
            - key: service_access.conf
              path: service_access.conf
            - key: app_default.conf
              path: app_default.conf
            - key: dm_svc.conf
              path: dm_svc.conf
            - key: mq_config.yaml
              path: mq_config.yaml
        - name: {{ .Release.Name }}-secret
          secret:
            secretName: {{ .Release.Name }}-secret
            items:
            - key: cluster.conf
              path: cluster.conf
        - name: wapi
          emptyDir: {}
        - name: ipc
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: brpc-volume
          emptyDir: {}
        - name: cfl-config
          emptyDir: {}
      dnsConfig:
         options:
           - name: single-request-reopen
           - name: use-vc
