apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-private-brpc2
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  ports:
    - name: eacpprivate-brpc2
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{add 4 .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{add 4 .Values.service.port }}
      {{- end}}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
