apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-thrift
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  ports:
    - name: eacpthrift
      port: 9992
      protocol: TCP
      targetPort: {{add 2 .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{add 2 .Values.service.port }}
      {{- end}}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
