apiVersion: v1
appVersion: "1.0.0"
description: A Helm sharemgnt-single service chart for Kubernetes
name: sharemgnt-single
version: 1.0.0
keywords:
  - sharemgnt-single
  - InformationSecurityFabric
