apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydra.secretname" . }}-dsn
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "hydra.labels" . | nindent 4 }}
type: Opaque
data:
  dsn: {{ include "hydra.dsn" . | b64enc | quote }}
  dsn2: {{ include "hydra.dsn" . | replace "parseTime=true&timeout=5s&readTimeout=5s&writeTimeout=5s" "parseTime=true&timeout=30s&readTimeout=30s&writeTimeout=30s" | b64enc | quote }}
