apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mount-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  secret.conf: |

    [cluster]
    db_user : {{ .Values.depServices.rds.user }}
    db_password : {{ .Values.depServices.rds.password }}

