# Default values for policy-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

nodeSelector: {}

namespace: policy

image:
  registry: ""
  service:
    repository: "as/policy-management"
    tag: ""
    pullPolicy: IfNotPresent

service:
  enableDualStack: false
  type: ClusterIP
  port: 9603
  debug: false
  logger:
    dir: /var/log/
    filename: server.log
    max_size: 2M
    backup_count: 5
    formatter: "%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(message)s"
  networkPolicy:
    syncInterval: 600
    topic: policy-data-topic
  language: zh_CN
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

env:
  language: en_US.UTF-8
  timezone: Asia/Shanghai
  GIN_MODE: release

aclOAuth:

depServices:
  rds:
    fromFile: false
    user: ""
    password: ""
    host: mariadb-mariadb-master.resource
    port: 3330
    type: mysql
    driver: proton-rds
    name: policy_mgnt
    system_id: ""
  hydra:
    publicHost: hydra-public
    publicPort: 4444
    publicProtocol: http
    administrativeHost: hydra-admin
    administrativePort: 4445
    administrativeProtocol: http
  mq: {}
  sharemgnt:
    host: sharemgnt
    port: 9600
  efast:
    publicHttpHost: efast-public
    publicHttpPort: 9123
    publicProtocol: http
  user-management:
    privateHost: user-management-private
    privatePort: 30980
    privateProtocol: http
  proton-application:
    host: deploy-web-service
    port: 18880
    protocol: http
  redis:
    connectType: sentinel|standalone|master-slave
    enableSSL: false
    connectInfo:
      username: ""
      password: ""
      host: ""
      port: 26379
      masterHost: ""
      masterPort: 26379
      slaveHost: ""
      slavePort: 26379
      sentinelHost: proton-redis-proton-redis-sentinel.resource.svc.cluster.local
      sentinelPort: 26379
      sentinelUsername: ""
      sentinelPassword: ""
      masterGroupName: mymaster
    secretName: ""
    caName: ""
    certName: ""
    keyName: ""

resources:
  requests:
    cpu: 31m
    memory: 100Mi
  limits:
    cpu: 2
    memory: 1Gi
