{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.service.repository }}:{{ .Values.image.service.tag }}
          imagePullPolicy: {{ .Values.image.service.pullPolicy }}
          env:
            {{- if .Values.service.logger}}
              - name: LOGOUT
                value: {{ .Values.service.logger | quote }}
            {{- end}}
            {{- if .Values.env.language}}
              - name: LANG
                value: {{ .Values.env.language | quote }}
              - name: LC_ALL
                value: {{ .Values.env.language | quote }}
            {{- end}}
            {{- if .Values.env.timezone}}
              - name: TZ
                value: {{ .Values.env.timezone | quote }}
            {{- end}}
            {{- if .Values.depServices.rds.type }}
              - name: DB_TYPE
                value: {{ .Values.depServices.rds.type | quote }}
            {{- end }}
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name:  DM_SVC_PATH
                value: /sysvol/conf/service_conf/
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-conf
            - secretRef:
                name: {{ .Release.Name }}-secret
          ports:
            - name: port
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            exec:
                command:
                  - /dist/bin/check_health/check_health
            initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.service.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.service.readinessProbe.failureThreshold }}
          livenessProbe:
            exec:
                command:
                  - /dist/bin/check_health/check_health
            initialDelaySeconds: {{ .Values.service.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.service.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.service.livenessProbe.failureThreshold }}
          # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
          # https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
          # 给负载均衡器和服务发现系统充分的“下线”时间。Pod 在即将被终止时，需要让其他服务
          # 发现机制（比如 Kubernetes Service）知道这个实例即将离线，以免继续将请求路由到它。
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: csv
              mountPath: /sysvol/conf/CUG
            - name: tds
              mountPath: /sysvol/conf/tds/lib/
            - name: ou
              mountPath: /sysvol/import_ou_files/
            - name: {{ .Release.Name }}-conf
              mountPath: /sysvol/conf/service_conf
            - name: {{ .Release.Name }}-mount-secret
              mountPath: /sysvol/conf/secret_conf
            - name: tmp-volume
              mountPath: /tmp
            - name: lock-ws
              mountPath: /var/lock/app
            - name: tmp-sysvol
              mountPath: /tmp/sysvol
            - name: sysvol-cache  
              mountPath: /sysvol/cache
            - name: sysvol-plugin
              mountPath: /sysvol/plugin
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: csv
          hostPath:
            path: /sysvol/conf/CUG
            type: DirectoryOrCreate
        - name: tds
          hostPath:
            path: /sysvol/conf/tds/lib/
            type: DirectoryOrCreate
        - name: ou
          hostPath:
            path: /sysvol/import_ou_files/
            type: DirectoryOrCreate
        - name: {{ .Release.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-conf
            items:
            - key: language.conf
              path: language.conf
            - key: service_access.conf
              path: service_access.conf
            - key: cluster.conf
              path: cluster.conf
            - key: app_default.conf
              path: app_default.conf
            - key: sigusr1.conf
              path: sigusr1.conf
            - key: dm_svc.conf
              path: dm_svc.conf
            - key: mq_config.yaml
              path: mq_config.yaml
        - name: {{ .Release.Name }}-mount-secret
          secret:
            secretName: {{ .Release.Name }}-mount-secret
            items:
            - key: secret.conf
              path: secret.conf
        - name: tmp-volume
          emptyDir: {}
        - name: lock-ws
          emptyDir: {}
        - name: tmp-sysvol
          emptyDir: {}
        - name: sysvol-cache
          emptyDir: {}
        - name: sysvol-plugin
          emptyDir: {}
      dnsConfig:
         options:
           - name: single-request-reopen
           - name: use-vc

