apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # REISD密码
  REDIS_USER: {{ .Values.depServices.redis.connectInfo.username | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.depServices.redis.connectInfo.password  | b64enc | quote }}
  REDIS_SENTINEL_USER: {{ .Values.depServices.redis.connectInfo.sentinelUsername | b64enc | quote }}
  REDIS_SENTINEL_PASSWORD: {{ .Values.depServices.redis.connectInfo.sentinelPassword  | b64enc | quote }}
